-- PRACTICAL 4
-- WRITE THE QUERY TO IMPLEMENT JOINS

DROP DATABASE IF EXISTS College;
CREATE DATABASE College;
USE College;

-- FACULTY TABLE
CREATE TABLE Faculty(
ID INT AUTO_INCREMENT PRIMARY KEY,
FIRSTNAME VARCHAR(100) NOT NULL,
LASTNAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(30) UNIQUE
);

-- DEPARTMENT TABLE
CREATE TABLE DEPARTMENT(
DeptID INT PRIMARY KEY,
DeptName VARCHAR(50) NOT NULL,
DeptLoc VARCHAR(12) NOT NULL
);

-- STUDENT TABLE
CREATE TABLE STUDENT(
S_ID INT AUTO_INCREMENT PRIMARY KEY,
FIRSTNAME VARCHAR(100) NOT NULL,
LASTNAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(30) UNIQUE
);

-- COURSE TABLE
CREATE TABLE COURSE(
CourseID INT PRIMARY KEY,
CourseName VARCHAR(100) NOT NULL,
DeptID INT,
FOREIGN KEY (DeptID) REFERENCES DEPARTMENT(DeptID)
);

-- INSERT STUDENT DATA
INSERT INTO STUDENT VALUES
(101,"ROHAN","THAKUR","rohan@gmail.com"),
(102,"MOHAN","THAKUR","mohan@gmail.com"),
(103,"RYAN","THAKUR","ryan@gmail.com"),
(104,"HEMAN","THAKUR","heman@gmail.com"),
(105,"HARMAN","THAKUR","harman@gmail.com");

-- INSERT DEPARTMENT DATA
INSERT INTO DEPARTMENT VALUES
(1,"CSE","BLOCK A"),
(2,"EE","BLOCK B"),
(3,"CIVIL","BLOCK C"),
(4,"MECHANICAL","BLOCK D");

-- INSERT COURSE DATA
INSERT INTO COURSE VALUES
(301,"MACHINE LEARNING",1),
(302,"OPERATING SYSTEM",1),
(303,"DIGITAL ELECTRONICS",2),
(304,"MATHEMATICS",2);

------------------------------------------------
-- JOIN QUERIES
------------------------------------------------

-- INNER JOIN
SELECT COURSE.CourseID, COURSE.CourseName, DEPARTMENT.DeptName
FROM COURSE
INNER JOIN DEPARTMENT
ON COURSE.DeptID = DEPARTMENT.DeptID;

-- LEFT JOIN
SELECT DEPARTMENT.DeptName, COURSE.CourseName
FROM DEPARTMENT
LEFT JOIN COURSE
ON DEPARTMENT.DeptID = COURSE.DeptID;

-- RIGHT JOIN
SELECT COURSE.CourseName, DEPARTMENT.DeptName
FROM COURSE
RIGHT JOIN DEPARTMENT
ON COURSE.DeptID = DEPARTMENT.DeptID;

-- FULL JOIN (Using UNION)
SELECT COURSE.CourseName, DEPARTMENT.DeptName
FROM COURSE
LEFT JOIN DEPARTMENT
ON COURSE.DeptID = DEPARTMENT.DeptID

UNION

SELECT COURSE.CourseName, DEPARTMENT.DeptName
FROM COURSE
RIGHT JOIN DEPARTMENT
ON COURSE.DeptID = DEPARTMENT.DeptID;

-- SELF JOIN
SELECT A.CourseName AS Course1, B.CourseName AS Course2
FROM COURSE A
JOIN COURSE B
ON A.DeptID = B.DeptID
WHERE A.CourseID <> B.CourseID;

------------------------------------------------
-- FINAL DATA CHECK
------------------------------------------------

SELECT * FROM STUDENT;
SELECT * FROM COURSE;
SELECT * FROM DEPARTMENT;
SELECT * FROM FACULTY;